version: "3.8"

services:
  db:
    container_name: pg_container
    image: postgres
    restart: always
    hostname: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: portfolio
      NAME: db
    volumes:
      - ./db-data:/var/lib/postgresql/data/
      - ./sql:/docker-entrypoint-initdb.d/:ro        
    ports:
      - "5432:5432"
    networks:
      - portfolio_network
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 800M
        reservations:
          cpus: '0.2'
          memory: 200M

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    hostname: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
      NAME: pgadmin
    ports:
      - "5050:80"
    networks:
      - portfolio_network
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 200M
        reservations:
          cpus: '0.01'
          memory: 20M      
  app:
    container_name: portfolio-api-dotnetcore
    image: portfolio-api:1.0.22
    hostname: portfolio
    restart: always
    build:
      context: .
    environment:
    - ASPNETCORE_ENVIRONMENT=Development
    - ASPNETCORE_URLS=http://+:4444
    ports:
      - 4444:4444
    networks:
      - portfolio_network      
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 500M
        reservations:
          cpus: '0.2'
          memory: 200M      
  keycloak:
      container_name: portfolio-keycloak
      image: bitnami/keycloak
      environment:
        KEYCLOAK_ADMIN: admin
        KEYCLOAK_ADMIN_PASSWORD: admin
        DB_VENDOR: POSTGRES
        DB_ADDR: db
        DB_DATABASE: keycloak
        DB_USER: postgres
        DB_SCHEMA: keycloak
        DB_PASSWORD: postgres

        # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the PostgreSQL JDBC driver documentation in order to use it.
        #JDBC_PARAMS: "ssl=true"
      ports:
      - "8180:8080"
      - "8787:8787" # debug port        

      depends_on:
        - db
      networks:
      - portfolio_network
      deploy:
        resources:
          limits:
            cpus: '0.1'
            memory: 500M
          reservations:
            cpus: '0.01'
            memory: 200M

volumes:
  postgres_data:
      driver: local
      
networks:
  portfolio_network:
    name: portfolio_network
    driver: bridge