version: "3.8"

services:
  db:
    container_name: pg_container
    image: postgres
    restart: always
    hostname: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: portfolio
      NAME: db
    ports:
      - "5432:5432"

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    hostname: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
      NAME: pgadmin
    ports:
      - "5050:80"
  app:
    container_name: portfolio-api-dotnetcore
    image: portfolio-api:1.0.22
    hostname: portfolio
    build:
      context: .
    environment:
    - ASPNETCORE_ENVIRONMENT=Development
    - ASPNETCORE_URLS=http://+:4444
    ports:
      - 4444:4444
