// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using portfolio.api.Persistence.Context;

#nullable disable

namespace portfolio.api.Persistence.migrations
{
    [DbContext(typeof(PortfolioDbContext))]
    [Migration("20231107214847_initial-migration")]
    partial class initialmigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("portfolio.api.Persistence.Entities.Knowledge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created");

                    b.Property<DateTime?>("Modified")
                        .ValueGeneratedOnUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("Id", "ProjectId")
                        .IsUnique();

                    b.ToTable("knowledges", "portfolio");

                    b.HasData(
                        new
                        {
                            Id = new Guid("072c5d14-24e9-497b-a46c-26a29d9348e8"),
                            Created = new DateTime(2023, 11, 7, 21, 48, 46, 687, DateTimeKind.Utc).AddTicks(1603),
                            Modified = new DateTime(2023, 11, 7, 21, 48, 46, 687, DateTimeKind.Utc).AddTicks(1605),
                            Name = "CSS",
                            ProjectId = new Guid("85532c07-d62b-458a-94a8-b3c2f7bd3086")
                        },
                        new
                        {
                            Id = new Guid("195a2c50-1490-4982-a757-3cf882c46fea"),
                            Created = new DateTime(2023, 11, 7, 21, 48, 46, 687, DateTimeKind.Utc).AddTicks(1637),
                            Modified = new DateTime(2023, 11, 7, 21, 48, 46, 687, DateTimeKind.Utc).AddTicks(1637),
                            Name = "HTML",
                            ProjectId = new Guid("85532c07-d62b-458a-94a8-b3c2f7bd3086")
                        });
                });

            modelBuilder.Entity("portfolio.api.Persistence.Entities.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTime?>("Modified")
                        .ValueGeneratedOnUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("projects", "portfolio");

                    b.HasData(
                        new
                        {
                            Id = new Guid("85532c07-d62b-458a-94a8-b3c2f7bd3086"),
                            Created = new DateTime(2023, 11, 7, 21, 48, 46, 687, DateTimeKind.Utc).AddTicks(7289),
                            Description = "Test Project with css and html",
                            Name = "Project 1"
                        },
                        new
                        {
                            Id = new Guid("700c0ec5-1e0f-41b4-bfed-e97e32ab7366"),
                            Created = new DateTime(2023, 11, 7, 21, 48, 46, 687, DateTimeKind.Utc).AddTicks(7311),
                            Description = "Test Project 2 description 2",
                            Name = "Project 2"
                        });
                });

            modelBuilder.Entity("portfolio.api.Persistence.Entities.Knowledge", b =>
                {
                    b.HasOne("portfolio.api.Persistence.Entities.Project", "Project")
                        .WithMany("Knowledges")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("portfolio.api.Persistence.Entities.Project", b =>
                {
                    b.Navigation("Knowledges");
                });
#pragma warning restore 612, 618
        }
    }
}
